# Generated by Django 3.1.2 on 2020-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Job_Type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('Discription', models.TextField(max_length=600)),
                ('vacancy', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Sex'), (7, 'Seven')])),
                ('salery', models.IntegerField(default=0)),
                ('Experience', models.IntegerField(default=1)),
            ],
        ),
    ]
