# Generated by Django 3.1.2 on 2020-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
        migrations.AlterField(
            model_name='job',
            name='Experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='salery',
            field=models.IntegerField(),
        ),
    ]
