# Generated by Django 3.1.2 on 2020-10-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201005_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='DiscRIPION',
            new_name='Discripion',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ExperIENCE',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salERY',
            new_name='salery',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='vacAnCY',
            new_name='vacancy',
        ),
    ]
