# Generated by Django 3.1.2 on 2020-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201005_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Published_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
